# Generated by Django 4.1.3 on 2026-08-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date',
        ),
    ]
