# Generated by Django 4.1.3 on 2026-08-24 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('activity_type', models.CharField(choices=[('multiple_choice', 'Çoktan Seçmeli'), ('fill_blank', 'Boşluk Doldurma'), ('true_false', 'Doğru / Yanlış')], max_length=30)),
                ('order', models.PositiveIntegerField(default=1)),
                ('isActive', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='courses.question')),
            ],
        ),
    ]
