# Generated by Django 4.1.3 on 2026-08-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_activity_question_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='flag',
            field=models.CharField(default='🌍', max_length=10),
        ),
    ]
