# Generated by Django 4.1.3 on 2026-08-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_language_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='flag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
