# Generated by Django 4.1.3 on 2026-08-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lessonprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('multiple_choice', 'Çoktan Seçmeli'), ('fill_blank', 'Boşluk Doldurma'), ('true_false', 'Doğru / Yanlış'), ('sentence_order', 'Cümle Oluşturma')], max_length=30),
        ),
    ]
