# Generated by Django 4.1.3 on 2026-09-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_questionresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
